<a href="https://colab.research.google.com/github/Berenice2018/DeepLearning/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

# Creating & saving NumPy arrays

In [0]:
x = np.array([1, 2, 3, 4, 5])

print(x)
print(type(x)) # print the type of x
x.dtype        # print the type of its elements

[1 2 3 4 5]
<class 'numpy.ndarray'>


dtype('int64')

NumPy arrays must have elements of the same data type.

Even though the Python list has mixed data types, the *array() *function creates a NumPy array with elements of all the same data type.

In [0]:
x2 = np.array([1, 2, "Hi"])
print(x2)
print('type of x2:', type(x2))
print('dtype:', x2.dtype)

['1' '2' 'Hi']
type of x2: <class 'numpy.ndarray'>
dtype: <U21


In [0]:
# NumPy upcasts 
x2 = np.array([1, 2, 3.5])

print(x2, x2.dtype) 

[1.  2.  3.5] float64


In [0]:
# downcast explicitly:
x2 = np.array([1.2, 3.5, 9.7], dtype= np.int64)
print(x2, x2.dtype)


[1 3 9] int64


In [0]:
# print the size of each dimension. 
# Since x has 1 dimension, it will print the length of the array

x.shape

(5,)

The shape of a 2-dimensional array is a tuple; number of rows and columns


In [0]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(y.shape)
print(y)


(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [0]:
# number of all elements

y.size

12

In [0]:
# save and load an array
np.save('my_y_array', y)
np.load('my_y_array.npy')

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Built-in Functions to Create ndarrays

In [0]:
# Create an array of zeros:
# @param: tuple indicating the shape of the array
# @param: dtype, for eample int

x = np.zeros((3,4))
print(x)
x = np.zeros((2,3), dtype = int)
print (x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]]


In [0]:
# Create an array of ones:
# @param: tuple indicating the shape of the array

x = np.ones((2,4), dtype=int)
print(x)

[[1 1 1 1]
 [1 1 1 1]]


In [0]:
x = np.full((2,4), 9)
print(x)

[[9 9 9 9]
 [9 9 9 9]]


In [0]:
# create an identity matrix
# @param: shape

x = np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [0]:
# create a square matrix and fill the diagonal
# @param: a set of values to fill the diagonal

x = np.diag([99,88,77,66])
print(x)

[[99  0  0  0]
 [ 0 88  0  0]
 [ 0  0 77  0]
 [ 0  0  0 66]]


In [0]:
# create an array of integers from zero. [0, param[
# @param: stop argument is exclusive
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [0]:
# create an array of integers
# @param: 1st argument is inclusive, 2nd one is exclusive: [a, b[
x = np.arange(5, 11)
print(x)

[ 5  6  7  8  9 10]


In [0]:
# create an array in a specified range and with a step
# @param: as above. 3rd param is the step (int)

x = np.arange(4, 25, 4)
print(x)

[ 4  8 12 16 20 24]


In [0]:
# create an array in a specified range and with a non-integer step 
# @param: start, stop, n for n evenly spaced numbers 
# start and stop are inclusive: [start, stop]

x = np.linspace(0, 25, 10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [0]:
# exclude the stop by setting the param endpoint=False:

x = np.linspace(0, 25, 20, endpoint=False)
print(x)

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.   11.25 12.5  13.75
 15.   16.25 17.5  18.75 20.   21.25 22.5  23.75]


In [0]:
# Convert any NumPy array into a specified shape:
# the new shape has to be compatible to the array size.

x = np.reshape(x, (4, 5))
print(x)
x = np.reshape(x, (2, 10))
print(x)

[[ 0.    1.25  2.5   3.75  5.  ]
 [ 6.25  7.5   8.75 10.   11.25]
 [12.5  13.75 15.   16.25 17.5 ]
 [18.75 20.   21.25 22.5  23.75]]
[[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.   11.25]
 [12.5  13.75 15.   16.25 17.5  18.75 20.   21.25 22.5  23.75]]


In [0]:
# chain fundtion calls

x = np.linspace(0, 10, 40, endpoint=False).reshape(5, 8)
print(x)

[[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75]
 [2.   2.25 2.5  2.75 3.   3.25 3.5  3.75]
 [4.   4.25 4.5  4.75 5.   5.25 5.5  5.75]
 [6.   6.25 6.5  6.75 7.   7.25 7.5  7.75]
 [8.   8.25 8.5  8.75 9.   9.25 9.5  9.75]]


In [0]:
# create an array with random float values between 0 and 1; [0, 1[ 
# @param: shape tuple
x = np.random.random((4,4))
print(x)

[[0.81201638 0.43104391 0.08230214 0.10112423]
 [0.89805729 0.48251593 0.23289989 0.77985833]
 [0.32580503 0.4495434  0.89810203 0.68639431]
 [0.85295332 0.15118613 0.33455525 0.3624027 ]]


In [0]:
# generate an array with random int within a particular range
# @param: start (inclusive), stop (exclusive) range, and the shape

x = np.random.randint(8, 22, (3,4))
print(x)

[[13 10 11 11]
 [17  9  8 21]
 [20 20 13 14]]


In [0]:
# generate an array with random floats  with mean, standard deviation
# @param: mean, std, shape tuple

x = np.random.normal(0, 0.2, size=(10, 10))
print(x)

[[ 0.15853484  0.11845152  0.06646205 -0.25229345 -0.21958606 -0.17906923
   0.14570771 -0.35442596 -0.12578895 -0.17795224]
 [-0.08879739 -0.00923171 -0.12222565 -0.00120037 -0.02361263 -0.09883286
   0.35332633 -0.07726044 -0.29218297 -0.34652278]
 [-0.07525939 -0.18445767 -0.23275805 -0.03945036 -0.41876771  0.2195576
  -0.0834159  -0.39055544 -0.05036867  0.02121945]
 [ 0.33072698 -0.3004115   0.1883272  -0.0286628  -0.19785588  0.4828132
  -0.18065774  0.08050895  0.28682558 -0.15387223]
 [ 0.23815911 -0.09865043 -0.03668869  0.07586253  0.32691454  0.40635901
   0.22515303 -0.04946772  0.0106129  -0.26549221]
 [-0.02014436  0.40486172 -0.11846475 -0.04130978  0.0954664  -0.14968423
  -0.04794997 -0.20119778  0.06546154 -0.04676929]
 [ 0.02680568 -0.1427188  -0.1105698   0.15742462 -0.21789887  0.03236188
  -0.16502551  0.07278756 -0.42112634  0.19999928]
 [-0.42506939 -0.15869656 -0.53040987 -0.03149008  0.19141551 -0.01612388
   0.13424714 -0.28078881  0.00921974 -0.17508927]
 [

# Accessing, Deleting, and Inserting Elements Into ndarrays

NumPy arrays are mutable. 

Use both positive and negative indices to access elements in the ndarray. Positive indices are used to access elements from the beginning of the array, while negative indices are used to access elements from the end of the array

In [0]:
x = np.array([1, 2, 3, 4, 5])

print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5


Delete elements using the np.delete(ndarray, elements, axis) function. 

This function deletes the given list of elements from the given ndarray along the specified axis. For rank 1 ndarrays the axis keyword is not required. 

For rank 2 ndarrays, axis = 0 is used to select rows, and axis = 1 is used to select columns.

In [0]:
# create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

# create a rank 2 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

print()
print('Original x = ', x)

# delete the first and last element of x
x = np.delete(x, [0,4])

print()
print('Modified x = ', x)
print()
print('Original Y = \n', Y)

# delete the first row of y
w = np.delete(Y, 0, axis=0)

# delete the first and last column of y
v = np.delete(Y, [0,2], axis=1)

print()
print('w = \n', w)

print()
print('v = \n', v)


Original x =  [1 2 3 4 5]

Modified x =  [2 3 4]

Original Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

w = 
 [[4 5 6]
 [7 8 9]]

v = 
 [[2]
 [5]
 [8]]


Append values to ndarrays using the np.append(ndarray, elements, axis) function. 
This function appends the given list of elements to ndarray along the specified axis

In [0]:
x = np.array([1, 2, 3, 4, 5])
Y = np.array([[1,2,3],[4,5,6]])

print()
print('Original x = ', x)

# append the integer 6 to x
x = np.append(x, 6)

print()
print('x = ', x)

# append the integer 7 and 8 to x
x = np.append(x, [7,8])

print()
print('x = ', x)
print()
print('Original Y = \n', Y)

# append a new row containing 7,8,9 to y
v = np.append(Y, [[7,8,9]], axis=0)

# append a new column containing 9 and 10 to y
q = np.append(Y,[[9],[10]], axis=1)

print()
print('v = \n', v)

print()
print('q = \n', q)


Original x =  [1 2 3 4 5]

x =  [1 2 3 4 5 6]

x =  [1 2 3 4 5 6 7 8]

Original Y = 
 [[1 2 3]
 [4 5 6]]

v = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

q = 
 [[ 1  2  3  9]
 [ 4  5  6 10]]


Insert the given list of elements to ndarray 

right before the given index along the specified axis. 

In [0]:
x = np.array([1, 2, 5, 6, 7])
Y = np.array([[1,2,3], [7,8,9]])

print()
print('Original x = ', x)

# insert the integer 3 and 4 between 2 and 5 in x. 
x = np.insert(x, 2, [3,4])

print()
print('x = ', x)
print()
print('Original Y = \n', Y)

# insert a row between the first and last row of y
w = np.insert(Y, 1, [4,5,6], axis=0)

# insert a column full of 5s between the first and second column of y
v = np.insert(Y, 1, 5, axis=1)

print()
print('w = \n', w)
print()
print('v = \n', v)


Original x =  [1 2 5 6 7]

x =  [1 2 3 4 5 6 7]

Original Y = 
 [[1 2 3]
 [7 8 9]]

w = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

v = 
 [[1 5 2 3]
 [7 5 8 9]]


Stack ndarrays on top of each other, or stack them side by side
 
 using either  *np.vstack()*  for vertical stacking, 
 
 or  *np.hstack()*  for horizontal stacking.
 
 The shape of the ndarrays must match.

In [0]:
x = np.array([1,2])
Y = np.array([[3,4],[5,6]])

print()
print('x = ', x)
print()
print('Y = \n', Y)

# stack x on top of Y
z = np.vstack((x, Y))

# stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y, x.reshape(2,1)))

print()
print('z = \n', z)
print()
print('w = \n', w)


x =  [1 2]

Y = 
 [[3 4]
 [5 6]]

z = 
 [[1 2]
 [3 4]
 [5 6]]

w = 
 [[3 4 1]
 [5 6 2]]
