<a href="https://colab.research.google.com/github/Berenice2018/DeepLearning/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

# Creating & saving NumPy arrays

In [0]:
import numpy as np

In [6]:
x = np.array([1, 2, 3, 4, 5])

print(x)
print(type(x)) # print the type of x
x.dtype        # print the type of its elements

[1 2 3 4 5]
<class 'numpy.ndarray'>


dtype('int64')

NumPy arrays must have elements of the same data type.

Even though the Python list has mixed data types, the *array() *function creates a NumPy array with elements of all the same data type.

In [0]:
x2 = np.array([1, 2, "Hi"])
print(x2)
print('type of x2:', type(x2))
print('dtype:', x2.dtype)

In [0]:
# NumPy upcasts 
x2 = np.array([1, 2, 3.5])

print(x2, x2.dtype) 

In [0]:
# downcast explicitly:
x2 = np.array([1.2, 3.5, 9.7], dtype= np.int64)
print(x2, x2.dtype)


In [0]:
# print the size of each dimension. 
# Since x has 1 dimension, it will print the length of the array

x.shape

The shape of a 2-dimensional array is a tuple; number of rows and columns


In [0]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(y.shape)
print(y)


In [0]:
# number of all elements

y.size

In [0]:
# save and load an array
np.save('my_y_array', y)
np.load('my_y_array.npy')

# Built-in Functions to Create ndarrays

In [0]:
# Create an array of zeros:
# @param: tuple indicating the shape of the array
# @param: dtype, for eample int

x = np.zeros((3,4))
print(x)
x = np.zeros((2,3), dtype = int)
print (x)

In [0]:
# Create an array of ones:
# @param: tuple indicating the shape of the array

x = np.ones((2,4), dtype=int)
print(x)

In [0]:
x = np.full((2,4), 9)
print(x)

In [0]:
# create an identity matrix
# @param: shape

x = np.eye(4)
print(x)

In [0]:
# create a square matrix and fill the diagonal
# @param: a set of values to fill the diagonal

x = np.diag([99,88,77,66])
print(x)

In [0]:
# create an array of integers from zero. [0, param[
# @param: stop argument is exclusive
x = np.arange(5)
print(x)

In [0]:
# create an array of integers
# @param: 1st argument is inclusive, 2nd one is exclusive: [a, b[
x = np.arange(5, 11)
print(x)

In [0]:
# create an array in a specified range and with a step
# @param: as above. 3rd param is the step (int)

x = np.arange(4, 25, 4)
print(x)

In [0]:
# create an array in a specified range and with a non-integer step 
# @param: start, stop, n for n evenly spaced numbers 
# start and stop are inclusive: [start, stop]

x = np.linspace(0, 25, 10)
print(x)

In [0]:
# exclude the stop by setting the param endpoint=False:

x = np.linspace(0, 25, 20, endpoint=False)
print(x)

In [0]:
# Convert any NumPy array into a specified shape:
# the new shape has to be compatible to the array size.

x = np.reshape(x, (4, 5))
print(x)
x = np.reshape(x, (2, 10))
print(x)

In [0]:
# chain fundtion calls

x = np.linspace(0, 10, 40, endpoint=False).reshape(5, 8)
print(x)

In [0]:
# create an array with random float values between 0 and 1; [0, 1[ 
# @param: shape tuple
x = np.random.random((4,4))
print(x)

In [0]:
# generate an array with random int within a particular range
# @param: start (inclusive), stop (exclusive) range, and the shape

x = np.random.randint(8, 22, (3,4))
print(x)

In [0]:
# generate an array with random floats  with mean, standard deviation
# @param: mean, std, shape tuple

x = np.random.normal(0, 0.2, size=(10, 10))
print(x)

In [7]:
# create a random permutation of integers 0 to 4
x = np.random.permutation(5)
print(x)

[3 4 1 0 2]


# Accessing, Deleting, and Inserting Elements Into ndarrays

NumPy arrays are mutable. 

Use both positive and negative indices to access elements in the ndarray. Positive indices are used to access elements from the beginning of the array, while negative indices are used to access elements from the end of the array

In [0]:
x = np.array([1, 2, 3, 4, 5])

print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])

Delete elements using the np.delete(ndarray, elements, axis) function. 

This function deletes the given list of elements from the given ndarray along the specified axis. For rank 1 ndarrays the axis keyword is not required. 

For rank 2 ndarrays, axis = 0 is used to select rows, and axis = 1 is used to select columns.

In [0]:
# create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

# create a rank 2 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

print()
print('Original x = ', x)

# delete the first and last element of x
x = np.delete(x, [0,4])

print()
print('Modified x = ', x)
print()
print('Original Y = \n', Y)

# delete the first row of y
w = np.delete(Y, 0, axis=0)

# delete the first and last column of y
v = np.delete(Y, [0,2], axis=1)

print()
print('w = \n', w)

print()
print('v = \n', v)

Append values to ndarrays using the np.append(ndarray, elements, axis) function. 
This function appends the given list of elements to ndarray along the specified axis

In [0]:
x = np.array([1, 2, 3, 4, 5])
Y = np.array([[1,2,3],[4,5,6]])

print()
print('Original x = ', x)

# append the integer 6 to x
x = np.append(x, 6)

print()
print('x = ', x)

# append the integer 7 and 8 to x
x = np.append(x, [7,8])

print()
print('x = ', x)
print()
print('Original Y = \n', Y)

# append a new row containing 7,8,9 to y
v = np.append(Y, [[7,8,9]], axis=0)

# append a new column containing 9 and 10 to y
q = np.append(Y,[[9],[10]], axis=1)

print()
print('v = \n', v)

print()
print('q = \n', q)

Insert the given list of elements to ndarray 

right before the given index along the specified axis. 

In [0]:
x = np.array([1, 2, 5, 6, 7])
Y = np.array([[1,2,3], [7,8,9]])

print()
print('Original x = ', x)

# insert the integer 3 and 4 between 2 and 5 in x. 
x = np.insert(x, 2, [3,4])

print()
print('x = ', x)
print()
print('Original Y = \n', Y)

# insert a row between the first and last row of y
w = np.insert(Y, 1, [4,5,6], axis=0)

# insert a column full of 5s between the first and second column of y
v = np.insert(Y, 1, 5, axis=1)

print()
print('w = \n', w)
print()
print('v = \n', v)

Stack ndarrays on top of each other, or stack them side by side
 
 using either  *np.vstack()*  for vertical stacking, 
 
 or  *np.hstack()*  for horizontal stacking.
 
 The shape of the ndarrays must match.

In [0]:
x = np.array([1,2])
Y = np.array([[3,4],[5,6]])

print()
print('x = ', x)
print()
print('Y = \n', Y)

# stack x on top of Y
z = np.vstack((x, Y))

# stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y, x.reshape(2,1)))

print()
print('z = \n', z)
print()
print('w = \n', w)

# Slicing ndarrays

1. ndarray[start : end]  # end index is excluded.
2. ndarray[start : ]
3. ndarray[ : end]  # end index is excluded.


Slicing only creates a view of the original array. This means that if you make changes in Z, you will be in effect changing the elements in X as well.

In [6]:
# create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

print()
print('original X = \n', X)
print()

# select the 2nd-4th rows and the 3rd- 5th columns
Z = X[1:4, 2:5]
print('Z = \n', Z)
Z = X[0:2, ]
print('Z = \n', Z)
Z = X[2:4,]
print('Z = \n', Z)

# select the same elements using method 2
W = X[1:, 2:5]


# select 1st- 3rd rows and the 3rd- 4th columns
Y = X[:3, 2:5]

print()
print('Y = \n', Y)

# select the 3rd row
v = X[2, :]

print()
print('v = ', v)

# select the 3rd column
q = X[:,2]

print()
print('q = ', q)


# select 3rd column, but return a rank 2 ndarray
R = X[:,2:3]

# We print R
print()
print('R = \n', R)


original X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
Z = 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Z = 
 [[10 11 12 13 14]
 [15 16 17 18 19]]

Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]

v =  [10 11 12 13 14]

q =  [ 2  7 12 17]

R = 
 [[ 2]
 [ 7]
 [12]
 [17]]


Create a new ndarray that contains a copy of the values in the slice by using the *np.copy() *function. The* np.copy(ndarray)* function creates a copy of the given ndarray. 

In [0]:
# create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

print()
print('X = \n', X)
print()

# create a copy of the slice using the np.copy() function
Z = np.copy(X[1:4,2:5])

# create a copy of the slice using the copy as a method
W = X[1:4,2:5].copy()

# change the last element in Z to 555
Z[2,2] = 555

# change the last element in W to 444
W[2,2] = 444

print()
print('X = \n', X)
print()
print('Z = \n', Z)
print()
print('W = \n', W)

*np.diag(ndarray, k=N) *  extracts the elements along the diagonal defined by N. 

As default is k=0, which refers to the main diagonal. 

Values of k > 0 are used to select elements in diagonals above the main diagonal, 

values of k < 0 are used to select elements in diagonals below the main diagonal.

 *np.unique(ndarray)*  returns the unique elements in the given ndarray

In [0]:
# ndarray with repeated values
X = np.array([[1,2,3],[5,2,8],[1,2,3]])

print()
print('X = \n', X)
print()

print('The unique elements in X are:',np.unique(X))

# Boolean Indexing, Set Operations, and Sorting

Select elements using logical arguments instead of explicit indices.

In [0]:
X = np.arange(25).reshape(5, 5)

X[X > 10]
X[X <= 7]
X[(X > 10) & (X < 17)]
# use boolean indexing to assign the elements that are between 10 and 17 the value of -1
X[(X > 10) & (X < 17)] = -1

print('X = \n', X)

Set operations:

useful when comparing ndarrays, for example, to find common elements between two ndarrays

In [0]:
#  np.intersect1d(x,y)
#  np.setdiff1d(x,y)
#  np.union1d(x,y)

x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])
print('x = ', x)
print()
print('y = ', y)

# use set operations to compare x and y:
print()
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))

*np.sort()* sorts  rank 1 and rank 2 ndarrays in different 

 The *np.sort()* function
 
sorts the ndrrays out of place, it doesn't change the original ndarray being sorted.
 
*ndarray.sort()* method sorts the ndarray in place

# Arithmetic operations, Broadcasting

Broadcasting is the term used to describe how NumPy handles element-wise arithmetic operations with ndarrays of different shapes. F. Ex., broadcasting is used implicitly when doing arithmetic operations between scalars and ndarrays.


Element-wise arithmetic operations on rank 2 ndarrays:

 The nsarrays must have the same shape or be broadcastable.

In [7]:
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)

print()
print('X = \n', X)
print()
print('Y = \n', Y)
print()

# perform basic element-wise operations using arithmetic symbols and functions
print('X + Y = \n', X + Y)
print()
print('add(X,Y) = \n', np.add(X,Y))
print()
print('X - Y = \n', X - Y)
print()
print('subtract(X,Y) = \n', np.subtract(X,Y))
print()
print('X * Y = \n', X * Y)
print()
print('multiply(X,Y) = \n', np.multiply(X,Y))
print()
print('X / Y = \n', X / Y)
print()
print('divide(X,Y) = \n', np.divide(X,Y))


X = 
 [[1 2]
 [3 4]]

Y = 
 [[5.5 6.5]
 [7.5 8.5]]

X + Y = 
 [[ 6.5  8.5]
 [10.5 12.5]]

add(X,Y) = 
 [[ 6.5  8.5]
 [10.5 12.5]]

X - Y = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

subtract(X,Y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

X * Y = 
 [[ 5.5 13. ]
 [22.5 34. ]]

multiply(X,Y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]

X / Y = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]

divide(X,Y) = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]


In [0]:
# np.exp(x)
# np.sqrt(x)
# np.power(x,2)


Statistical functions 

In [9]:
X.mean(axis=0)
X.sum(axis=1)

X.std()
X.std(axis=1)

np.median(X,axis=1)

X.min(axis=1)
X.max(axis=0)


X = np.array([[1,2], [3,4]])
print()
print('X = \n', X)
print()

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print('my sol: ', X.min(axis=0))
print('my sol: ', np.mean(X.min(axis=0)))
print(np.min(X, axis=0))
print(np.mean(np.min(X, axis=0))) # gets the minimum value of each column and calculates their mean

print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))


X = 
 [[1 2]
 [3 4]]

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]
my sol:  [1 2]
my sol:  1.5
[1 2]
1.5

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


add single numbers to all the elements of an ndarray without  loops.

 NumPy is working behind the scenes to broadcast 3 along the ndarray so that they have the same shape.

In [0]:
X = np.array([[1,2], [3,4]])
print()
print('X = \n', X)
print()

print('3 * X = \n', 3 * X)
print()
print('3 + X = \n', 3 + X)
print()
print('X - 3 = \n', X - 3)
print()
print('X / 3 = \n', X / 3)

In [0]:
x = np.array([1,2,3])
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
Z = np.array([1,2,3]).reshape(3,1)

print()
print('x = ', x)
print()
print('Y = \n', Y)
print()
print('Z = \n', Z)
print()

print('x + Y = \n', x + Y)
print()
print('Z + Y = \n',Z + Y)